services:
  - type: web
    name: dd-sons-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        value: your-production-secret-key-here
      - key: DATABASE_URL
        value: sqlite:///dd_sons.db
